/* Automatically generated by './build/bin/build-entry.js' */

import Button from './components/button/package/index.ts';
import Loading from './components/Loading/src/index.ts';
import checkbox from './components/checkbox//src/index.ts';
import europeWarranty from './components/europe-warranty/src/index.ts';
import FloatContactShopper from './components/float-contact-shopper/src/index.ts';
import Image from './components/image/src/index.ts';
import GButton from './components/g-button/src/index.ts';
import GInput from './components/input/src/index.ts';

import locale from 'g-ui/src/locale/index';

import './utils/framework/vue/plugin/lazyload.js';

const components = [
  Button,
  Loading,
  checkbox,
  europeWarranty,
  FloatContactShopper,
  Image,
  GButton,
  GInput
];

const install = function(Vue, opts = {}) {

  locale.use(opts.locale)

  components.forEach(component => {
    Vue.component(component.name, component);
  });

  Vue.prototype.$ELEMENT = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };


};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '0.0.1',
  install,
  Button
};
